// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tarotReader_MVC.Migrations
{
    [DbContext(typeof(MvcTarotsContext))]
    [Migration("20220707144501_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tarots", b =>
                {
                    b.Property<int>("TarotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TarotId"), 1L, 1);

                    b.Property<string>("TarotCareer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarotDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarotLove")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarotName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TarotWealth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TarotId");

                    b.ToTable("Tarots");
                });
#pragma warning restore 612, 618
        }
    }
}
